### ISSUE TITLE
Add password protection

### ISSUE THREAD

**Issue by NoodlesDev987** [modmail-dev/logviewer#33]
Hi, can you please add config option to set PASSWORD in .env, when you want to show log you need to enter that password from .env. This would be to protect showing logs to unwanted people if you are not patreon to have oauth.

**Comment by Mapegz** [comment]
This would be greatly helpful, just a single link and the entire log gets exposed to unwanted audience. 

**EDIT:-** It would be better if you open this request in the [ModLog Webserver Repository](https://github.com/kyb3r/logviewer) instead

**Comment by lorenzo132** [comment]
can be closed, this is a patreon only feature using discord oauth
