### ISSUE TITLE
Docker Hub image is outdated by a year

### ISSUE THREAD

**Issue by EthanC** [modmail-dev/logviewer#66]
The [kyb3rr/logviewer](https://hub.docker.com/r/kyb3rr/logviewer) image on Docker Hub reports it was last updated "a year ago," leaving those of us who would like to host via Docker to build the image manually and not have the ability to update automatically.

Are there any plans to fix this? The same is true for the [kyb3rr/modmail](https://hub.docker.com/r/kyb3rr/modmail) image (https://github.com/kyb3r/modmail/issues/3144).

**Comment by Saturn745** [comment]
#67

**Comment by Taaku18** [comment]
You can use this image instead, hosted on the GitHub Container Registry: `docker pull ghcr.io/kyb3r/logviewer:master`.
