### ISSUE TITLE
[BUG] Logviewer Avatar Broken

### ISSUE THREAD

**Issue by madscientista** [modmail-dev/logviewer#69]
### Bot Version

4.0.1

### How are you hosting Modmail?

Other

### Error Logs

https://hastebin.cc/kedasesope

### Screenshots

**Broken Avatar ScreenShot:** https://i.imgur.com/UK8G23C.png
**Fine on mobile?:** https://files.catbox.moe/y8t4qb.jpeg

### Additional Information

Please fix this avatar. Or atleast make it that the avatar is the user that closed it.

**Comment by raidensakura** [comment]
Duplicate of #46 
Fix in #68
